from housing_projections.analysis import compute_model_comparison
from housing_projections.data import (
    load_data,
    make_data_dict,
    select_spatial_sample,
    validate_data_path,
)
from housing_projections.diagnostics import full_diagnostics
from housing_projections.eda import (
    classify_lsoas,
    compute_agreement_stats,
    compute_autocorrelations,
    compute_crosscorrelations,
    compute_crosscorrelations_prewhitened,
    compute_overall_correlation,
    full_agreement_analysis,
    plot_annual_p_vs_e,
    plot_autocorrelations,
    plot_category_breakdown,
    plot_category_examples,
    plot_census_stock_maps,
    plot_census_stocks,
    plot_change_hotspots,
    plot_crosscorrelations,
    plot_cumulative_vs_intercensal,
    plot_distributions_by_year,
    plot_intercensal_change_histogram_map,
    plot_intercensal_change_map,
    plot_lag_candidates,
    plot_mean_change_maps,
    plot_mean_trends,
    plot_morans_i_by_year,
    plot_per_area_correlation,
    plot_sign_disagreements,
    plot_source_disagreement_map,
    plot_spatial_autocorrelation_change,
    plot_spatial_distribution,
    plot_stock_scatter,
    plot_total_agreement,
    plot_year_correlation,
)
from housing_projections.multimodality import (
    ModeClassificationThresholds,
    adjusted_diagnostics_report,
    adjusted_diagnostics_summary,
    classify_multimodality,
    classify_scalar_multimodality,
    compute_loglik_gap,
    compute_logp_gap,
    compute_switch_rates,
    derive_loglik_var,
    lag_vars_in_trace,
    multimodality_report,
    resolve_stuck_areas,
    verify_resolution,
)
from housing_projections.outliers import (
    apply_outlier_exclusion,
    plot_hard_outlier_areas,
    plot_outlier_areas,
    plot_outlier_map,
    plot_soft_outlier_areas,
)
from housing_projections.plots import (
    plot_parameter_trace,
    plot_posterior_predictive,
    plot_prior_predictive,
    plot_residual_analysis,
    plot_sample_areas,
    plot_spatial_diagnostics,
)
from housing_projections.reporting import full_report, run_comparison_reports
from housing_projections.sensitivity import (
    compute_model_agreement_matrix,
    compute_z_ensemble,
    compute_z_model_sensitivity,
    plot_model_agreement_matrix,
    plot_sensitivity_vs_disagreement,
    plot_z_range_distribution,
    plot_z_sensitivity_map,
)
from housing_projections.spatial import (
    SpatialLagTransformer,
    add_spatial_lag_features,
    build_spatial_weights,
    build_weights_libpysal,
    compute_morans_i,
    compute_morans_i_by_year,
)

__all__ = [
    # data
    "load_data",
    "make_data_dict",
    "select_spatial_sample",
    "validate_data_path",
    # diagnostics
    "full_diagnostics",
    "compute_model_comparison",
    # eda
    "plot_census_stocks",
    "plot_stock_scatter",
    "plot_cumulative_vs_intercensal",
    "compute_overall_correlation",
    "plot_per_area_correlation",
    "plot_annual_p_vs_e",
    "plot_distributions_by_year",
    "plot_mean_trends",
    "plot_year_correlation",
    "compute_autocorrelations",
    "compute_crosscorrelations",
    "compute_crosscorrelations_prewhitened",
    "plot_autocorrelations",
    "plot_crosscorrelations",
    "compute_agreement_stats",
    "classify_lsoas",
    "full_agreement_analysis",
    "plot_total_agreement",
    "plot_category_breakdown",
    "plot_category_examples",
    "plot_lag_candidates",
    "plot_sign_disagreements",
    "plot_morans_i_by_year",
    "plot_spatial_distribution",
    "plot_mean_change_maps",
    "plot_source_disagreement_map",
    "plot_intercensal_change_map",
    "plot_census_stock_maps",
    "plot_intercensal_change_histogram_map",
    "plot_change_hotspots",
    "plot_spatial_autocorrelation_change",
    # multimodality
    "ModeClassificationThresholds",
    "compute_switch_rates",
    "compute_loglik_gap",
    "compute_logp_gap",
    "classify_multimodality",
    "classify_scalar_multimodality",
    "resolve_stuck_areas",
    "verify_resolution",
    "lag_vars_in_trace",
    "derive_loglik_var",
    "adjusted_diagnostics_report",
    "multimodality_report",
    "adjusted_diagnostics_summary",
    # outliers
    "apply_outlier_exclusion",
    "plot_outlier_areas",
    "plot_hard_outlier_areas",
    "plot_soft_outlier_areas",
    "plot_outlier_map",
    # plots
    "plot_sample_areas",
    "plot_posterior_predictive",
    "plot_prior_predictive",
    "plot_residual_analysis",
    "plot_parameter_trace",
    "plot_spatial_diagnostics",
    # reporting
    "full_report",
    "run_comparison_reports",
    # sensitivity
    "compute_z_model_sensitivity",
    "compute_model_agreement_matrix",
    "compute_z_ensemble",
    "plot_z_sensitivity_map",
    "plot_model_agreement_matrix",
    "plot_z_range_distribution",
    "plot_sensitivity_vs_disagreement",
    # spatial
    "build_weights_libpysal",
    "build_spatial_weights",
    "compute_morans_i",
    "compute_morans_i_by_year",
    "add_spatial_lag_features",
    "SpatialLagTransformer",
]
