"""
Builds notebooks/8.0-cd-az3_estimates_dashboard.py -- a marimo notebook with
Phase A's CSVs + the borough boundary GeoJSON embedded directly as
gzip+base64 string literals in its own source, so it has ZERO runtime file
or private-package dependency (no housing_projections/gla_data/geopandas
import, no filesystem read). That's required for
`marimo export html-wasm` to produce a single, truly self-contained static
HTML file that non-technical stakeholders can open with no server and no
access to this repo's private dataset -- see
docs/estimates-dashboard-report-plan.md Phase B.

Re-run this whenever results/artifacts/az3_year_estimates/*.csv or
borough_boundaries.geojson change; it always overwrites the notebook file
from scratch (the notebook itself is generated output, not hand-edited).

Usage
-----
    pixi run python scripts/build_dashboard.py
"""
import base64
import gzip
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = _REPO_ROOT / 'results' / 'artifacts' / 'az3_year_estimates'
OUTPUT_PATH = _REPO_ROOT / 'notebooks' / '8.0-cd-az3_estimates_dashboard.py'


def _encode(path):
    raw = path.read_bytes()
    return base64.b64encode(gzip.compress(raw, compresslevel=9)).decode('ascii')


def main():
    blobs = {
        'AREA_YEAR_ESTIMATES_GZB64': _encode(DATA_DIR / 'area_year_estimates.csv'),
        'AREA_SCENARIOS_GZB64': _encode(DATA_DIR / 'area_scenarios.csv'),
        'AREA_TIER_SUMMARY_GZB64': _encode(DATA_DIR / 'area_tier_summary.csv'),
        'BOROUGH_LONDON_TOTALS_GZB64': _encode(DATA_DIR / 'borough_london_totals.csv'),
        'BOROUGH_BOUNDARIES_GZB64': _encode(DATA_DIR / 'borough_boundaries.geojson'),
    }
    for name, blob in blobs.items():
        print(f'{name}: {len(blob) / 1e3:.0f} KB (base64)')

    notebook_source = NOTEBOOK_TEMPLATE.format(**blobs)
    OUTPUT_PATH.write_text(notebook_source)
    print(f'\nWrote {OUTPUT_PATH} ({OUTPUT_PATH.stat().st_size / 1e6:.1f} MB)')


NOTEBOOK_TEMPLATE = '''import marimo

__generated_with = "0.23.4"
app = marimo.App(width="medium", app_title="AZ3 dwelling-change estimates")


@app.cell(hide_code=True)
def _():
    import marimo as mo
    return (mo,)


@app.cell(hide_code=True)
def _():
    # Generated by scripts/build_dashboard.py -- do not hand-edit the blobs
    # below. Re-run that script after Phase A's CSVs change.
    import base64
    import gzip
    import io
    import json

    import altair as alt
    import pandas as pd

    def _load_csv(b64_gz):
        raw = gzip.decompress(base64.b64decode(b64_gz))
        return pd.read_csv(io.StringIO(raw.decode("utf-8")))

    def _load_geojson(b64_gz):
        raw = gzip.decompress(base64.b64decode(b64_gz))
        return json.loads(raw.decode("utf-8"))

    _AREA_YEAR_ESTIMATES_GZB64 = "{AREA_YEAR_ESTIMATES_GZB64}"
    _AREA_SCENARIOS_GZB64 = "{AREA_SCENARIOS_GZB64}"
    _AREA_TIER_SUMMARY_GZB64 = "{AREA_TIER_SUMMARY_GZB64}"
    _BOROUGH_LONDON_TOTALS_GZB64 = "{BOROUGH_LONDON_TOTALS_GZB64}"
    _BOROUGH_BOUNDARIES_GZB64 = "{BOROUGH_BOUNDARIES_GZB64}"

    area_year_estimates = _load_csv(_AREA_YEAR_ESTIMATES_GZB64)
    area_scenarios = _load_csv(_AREA_SCENARIOS_GZB64)
    area_tier_summary = _load_csv(_AREA_TIER_SUMMARY_GZB64)
    borough_london_totals = _load_csv(_BOROUGH_LONDON_TOTALS_GZB64)
    borough_boundaries = _load_geojson(_BOROUGH_BOUNDARIES_GZB64)
    return (
        alt,
        area_scenarios,
        area_tier_summary,
        area_year_estimates,
        borough_boundaries,
        borough_london_totals,
        json,
        pd,
    )


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
        # London dwelling-stock change, 2012-2021 -- AZ3 model estimates

        Every figure here comes from a statistical model's estimate of annual dwelling-stock
        change (`z`) per London LSOA, reconciled against multiple administrative records.
        For this round of modelling, the 2011/2021 Census totals are treated as exactly
        correct -- a deliberate simplifying assumption, not a claim that the Census itself has
        zero error; that assumption could be relaxed in future work. Given that assumption, the
        **total** change over the decade adds no further modelling uncertainty for any area;
        the **year-by-year breakdown** within that decade is not equally certain everywhere, so
        every area below is labelled with one of three confidence tiers:

        - **Tier 1 -- Confident**: a single trustworthy year-by-year path.
        - **Tier 2 -- Ambiguous, resolved**: 2-3 distinct, labelled possible stories (e.g.
          "60% chance the change concentrated in 2019, 40% chance 2021"), each with its
          relative likelihood.
        - **Tier 2 -- Ambiguous, unresolved / Tier 3 -- Diffuse**: the total change carries no
          further modelling uncertainty (under the assumption above) but no small set of
          clean stories describes the year-by-year pattern -- reported as the total only, not
          a misleading single-year guess.
        """
    )
    return


@app.cell(hide_code=True)
def _(area_tier_summary, borough_london_totals, mo):
    _london_total = borough_london_totals[
        (borough_london_totals["geography"] == "London")
        & (borough_london_totals["year"] == "total")
    ].iloc[0]

    _n = len(area_tier_summary)
    _tier_counts = area_tier_summary["tier"].value_counts()
    _pct_tier1 = 100 * _tier_counts.get("tier1", 0) / _n
    _pct_tier2 = 100 * _tier_counts.get("tier2", 0) / _n
    _pct_tier3 = 100 * _tier_counts.get("tier3", 0) / _n

    mo.hstack(
        [
            mo.stat(
                value=f"{{_london_total['z_total_mean']:,.0f}}",
                label="London total dwelling change 2012-2021",
                caption=(
                    f"90% CI: {{_london_total['z_total_lo90']:,.0f}} to "
                    f"{{_london_total['z_total_hi90']:,.0f}}"
                ),
            ),
            mo.stat(value=f"{{_pct_tier1:.0f}}%", label="Areas confident (Tier 1)"),
            mo.stat(value=f"{{_pct_tier2:.0f}}%", label="Areas with labelled scenarios (Tier 2)"),
            mo.stat(value=f"{{_pct_tier3:.0f}}%", label="Areas diffuse / total-only (Tier 3)"),
        ],
        justify="space-around",
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        """
        ## Which kinds of areas tend to be less certain?

        Confidence in the year-by-year picture is not random -- it depends strongly on how
        much change an area had to account for, and only weakly on which borough it's in.
        """
    )
    return


@app.cell(hide_code=True)
def _(area_tier_summary, pd):
    _bins = [0, 10, 25, 50, 100, 250, 1e9]
    _labels = ["0-10", "10-25", "25-50", "50-100", "100-250", "250+"]
    _tmp = area_tier_summary.copy()
    _tmp["abs_D"] = _tmp["D"].abs()
    _tmp["D_band"] = pd.cut(_tmp["abs_D"], bins=_bins, labels=_labels, include_lowest=True)
    d_band_stats = (
        _tmp.groupby("D_band")["tier"]
        .value_counts(normalize=True)
        .unstack(fill_value=0)
        .reset_index()
        .melt(id_vars="D_band", var_name="tier", value_name="fraction")
    )
    d_band_stats["fraction"] = d_band_stats["fraction"] * 100
    return (d_band_stats,)


@app.cell(hide_code=True)
def _(alt, d_band_stats, mo):
    _band_order = ["0-10", "10-25", "25-50", "50-100", "100-250", "250+"]
    _tier_labels = {{
        "tier1": "Confident", "tier2": "Labelled scenarios", "tier3": "Diffuse / total-only"
    }}
    _named = d_band_stats.copy()
    _named["tier_label"] = _named["tier"].map(_tier_labels)

    _chart = (
        alt.Chart(_named)
        .mark_bar()
        .encode(
            x=alt.X("D_band:N", title="Size of decade change (dwellings, absolute)",
                    sort=_band_order),
            y=alt.Y("fraction:Q", title="% of areas"),
            color=alt.Color(
                "tier_label:N", title="Confidence group",
                scale=alt.Scale(
                    domain=["Confident", "Labelled scenarios", "Diffuse / total-only"],
                    range=["#4c78a8", "#f2a900", "#b3b3b3"],
                ),
            ),
            tooltip=["D_band", "tier_label", alt.Tooltip("fraction:Q", format=".0f")],
        )
        .properties(width=600, height=280, title="Confidence group by size of change")
    )
    mo.vstack(
        [
            _chart,
            mo.md(
                "*Smaller changes are either very confidently tracked or, if there was next to "
                "no recorded activity behind them, diffuse; the largest changes are almost "
                "always ambiguous between a few labelled scenarios rather than confidently "
                "pinned to one year.*"
            ),
        ]
    )
    return


@app.cell(hide_code=True)
def _(alt, borough_stats, mo):
    _chart = (
        alt.Chart(borough_stats)
        .mark_bar()
        .encode(
            x=alt.X("pct_tier1:Q", title="% of areas confident (Tier 1)"),
            y=alt.Y("borough_name:N", title=None, sort="-x"),
            color=alt.Color("D_total:Q", title="Total change", scale=alt.Scale(scheme="blues")),
            tooltip=[
                "borough_name",
                alt.Tooltip("pct_tier1:Q", format=".0f"),
                alt.Tooltip("D_total:Q", title="Total change", format=",.0f"),
            ],
        )
        .properties(width=600, height=520, title="Confidence by borough")
    )
    mo.vstack(
        [
            _chart,
            mo.md(
                "*Boroughs with more total change to account for (darker bars) tend to have "
                "fewer confidently-tracked areas -- the same size-of-change pattern as above, "
                "not a borough-specific effect.*"
            ),
        ]
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md("""## Explore by borough""")
    return


@app.cell(hide_code=True)
def _(area_tier_summary):
    _borough_tier_counts = (
        area_tier_summary.groupby("borough_name")["tier"]
        .value_counts(normalize=True)
        .unstack(fill_value=0)
        * 100
    )
    borough_stats = (
        area_tier_summary.groupby("borough_name")
        .agg(n_areas=("area", "size"), D_total=("D", "sum"))
        .join(_borough_tier_counts)
        .reset_index()
        .rename(columns={{"tier1": "pct_tier1", "tier2": "pct_tier2", "tier3": "pct_tier3"}})
    )
    for _col in ["pct_tier1", "pct_tier2", "pct_tier3"]:
        if _col not in borough_stats.columns:
            borough_stats[_col] = 0.0
    return (borough_stats,)


@app.cell(hide_code=True)
def _(mo):
    map_metric = mo.ui.dropdown(
        options={{
            "% of areas confident (Tier 1)": "pct_tier1",
            "% of areas diffuse / total-only (Tier 3)": "pct_tier3",
            "Total dwelling change (decade)": "D_total",
        }},
        value="% of areas confident (Tier 1)",
        label="Colour boroughs by",
    )
    map_metric
    return (map_metric,)


@app.cell(hide_code=True)
def _(alt, borough_boundaries, borough_stats, map_metric):
    _chart = (
        alt.Chart(alt.Data(values=borough_boundaries["features"]))
        .mark_geoshape(stroke="white", strokeWidth=0.5)
        .transform_lookup(
            lookup="properties.borough_name",
            from_=alt.LookupData(
                borough_stats, "borough_name", ["pct_tier1", "pct_tier2", "pct_tier3", "D_total"]
            ),
        )
        .encode(
            color=alt.Color(f"{{map_metric.value}}:Q", title=map_metric.selected_key),
            tooltip=[
                alt.Tooltip("properties.borough_name:N", title="Borough"),
                alt.Tooltip("pct_tier1:Q", title="% Tier 1", format=".0f"),
                alt.Tooltip("pct_tier2:Q", title="% Tier 2", format=".0f"),
                alt.Tooltip("pct_tier3:Q", title="% Tier 3", format=".0f"),
                alt.Tooltip("D_total:Q", title="Total change", format=",.0f"),
            ],
        )
        .properties(width=520, height=420, title="London boroughs")
    )
    _chart
    return


@app.cell(hide_code=True)
def _(borough_london_totals, mo):
    borough_choice = mo.ui.dropdown(
        options=sorted(borough_london_totals["geography"].unique()),
        value="London",
        label="Show year-by-year total for",
    )
    borough_choice
    return (borough_choice,)


@app.cell(hide_code=True)
def _(alt, borough_choice, borough_london_totals, mo):
    _trend = borough_london_totals[
        (borough_london_totals["geography"] == borough_choice.value)
        & (borough_london_totals["year"] != "total")
    ].copy()
    _trend["year"] = _trend["year"].astype(int)

    _band = (
        alt.Chart(_trend)
        .mark_area(opacity=0.25)
        .encode(x=alt.X("year:O", title="Year"), y="z_total_lo90:Q", y2="z_total_hi90:Q")
    )
    _line = (
        alt.Chart(_trend)
        .mark_line(point=True)
        .encode(x=alt.X("year:O", title="Year"), y=alt.Y("z_total_mean:Q", title="Dwelling change"))
    )
    mo.ui.altair_chart(
        (_band + _line).properties(
            width=650, height=280, title=f"{{borough_choice.value}} -- annual dwelling change (90% CI)"
        )
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        """
        ## Does uncertainty add up consistently across scales?

        A basic sanity check: if we (incorrectly) added up each individual LSOA's own
        uncertainty range one by one, would we get the same range the model actually reports
        for the borough or London total selected above? We shouldn't, and we don't --
        individual areas' timing uncertainty doesn't all point the same way at once, so the
        ranges should *not* simply add up. The model's actual borough/London-level range is
        genuinely narrower than that naive sum, which is exactly what should happen if
        uncertainty is being combined correctly across scales, from the same underlying
        LSOA-level figures, rather than estimated separately at each level.
        """
    )
    return


@app.cell(hide_code=True)
def _(area_tier_summary, area_year_estimates, borough_choice, pd):
    _yr = area_year_estimates.merge(area_tier_summary[["area", "borough_name"]], on="area")
    _yr["ci_width"] = _yr["z_hi90"] - _yr["z_lo90"]
    if borough_choice.value == "London":
        _naive = _yr.groupby("year")["ci_width"].sum()
    else:
        _naive = _yr[_yr["borough_name"] == borough_choice.value].groupby("year")["ci_width"].sum()
    consistency_check = pd.DataFrame({{"naive_sum_of_area_ranges": _naive}}).reset_index()
    return (consistency_check,)


@app.cell(hide_code=True)
def _(alt, borough_choice, borough_london_totals, consistency_check, mo):
    _actual = borough_london_totals[
        (borough_london_totals["geography"] == borough_choice.value)
        & (borough_london_totals["year"] != "total")
    ].copy()
    _actual["year"] = _actual["year"].astype(int)
    _actual["actual_range"] = _actual["z_total_hi90"] - _actual["z_total_lo90"]

    _cmp = consistency_check.merge(_actual[["year", "actual_range"]], on="year")
    _long = _cmp.melt(id_vars="year", var_name="series", value_name="range_width")
    _label_map = {{
        "naive_sum_of_area_ranges": "If you (wrongly) added up every area's own range",
        "actual_range": f"Actual {{borough_choice.value}} range (correct)",
    }}
    _long["series"] = _long["series"].map(_label_map)

    _chart = (
        alt.Chart(_long)
        .mark_bar()
        .encode(
            x=alt.X("year:O", title="Year"),
            y=alt.Y("range_width:Q", title="90% range width (dwellings)"),
            color=alt.Color("series:N", title=None),
            xOffset="series:N",
            tooltip=["year", "series", alt.Tooltip("range_width:Q", format=",.0f")],
        )
        .properties(
            width=650, height=280,
            title=f"{{borough_choice.value}}: naive vs. actual uncertainty range",
        )
    )

    _avg_ratio = (_cmp["actual_range"] / _cmp["naive_sum_of_area_ranges"]).mean()
    mo.vstack(
        [
            mo.ui.altair_chart(_chart),
            mo.md(
                f"*For {{borough_choice.value}}, the model's actual range is on average "
                f"**{{_avg_ratio:.0%}}** of what naively adding up every area's own range would "
                f"give -- uncertainty shrinks in relative terms as you aggregate, as it should.*"
            ),
        ]
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md("""## Look up a specific LSOA""")
    return


@app.cell(hide_code=True)
def _(area_tier_summary, mo):
    lsoa_search = mo.ui.text(placeholder="e.g. E01002702", label="LSOA code")
    borough_filter = mo.ui.dropdown(
        options=["(all boroughs)"] + sorted(area_tier_summary["borough_name"].unique()),
        value="(all boroughs)",
        label="or filter by borough",
    )
    mo.hstack([lsoa_search, borough_filter], justify="start", gap=2)
    return borough_filter, lsoa_search


@app.cell(hide_code=True)
def _(area_tier_summary, borough_filter, lsoa_search, mo):
    _filtered = area_tier_summary
    if borough_filter.value != "(all boroughs)":
        _filtered = _filtered[_filtered["borough_name"] == borough_filter.value]
    if lsoa_search.value.strip():
        _filtered = _filtered[
            _filtered["area"].str.contains(lsoa_search.value.strip(), case=False, na=False)
        ]
    _cols = ["area", "borough_name", "D", "tier", "tier_subtype"]
    lsoa_table = mo.ui.table(_filtered[_cols].reset_index(drop=True), selection="single", page_size=8)
    lsoa_table
    return (lsoa_table,)


@app.cell(hide_code=True)
def _(alt, area_scenarios, area_tier_summary, area_year_estimates, json, lsoa_table, mo, pd):
    mo.stop(
        len(lsoa_table.value) == 0,
        mo.md("*Select a row above (or several -- the chart below follows the first one "
              "selected) to see that LSOA's year-by-year breakdown.*"),
    )

    _area = lsoa_table.value.iloc[0]["area"]
    _tier_row = area_tier_summary[area_tier_summary["area"] == _area].iloc[0]
    _year_rows = area_year_estimates[area_year_estimates["area"] == _area].sort_values("year")
    _years = _year_rows["year"].tolist()

    _is_resolved_tier2 = _tier_row["tier"] == "tier2" and _tier_row["tier_subtype"] == "resolved"

    _band = (
        alt.Chart(_year_rows)
        .mark_area(opacity=0.12 if _is_resolved_tier2 else 0.25, color="gray")
        .encode(x=alt.X("year:O", title="Year"), y="z_lo90:Q", y2="z_hi90:Q")
    )

    if _is_resolved_tier2:
        _scenarios = area_scenarios[area_scenarios["area"] == _area]
        _scenario_rows = []
        for r in _scenarios.itertuples():
            _profile = json.loads(r.year_profile)
            for _yr, _z in zip(_years, _profile):
                _scenario_rows.append(
                    {{"year": _yr, "z": _z, "scenario": f"{{r.scenario_label}} ({{r.weight:.0%}})"}}
                )
        _scenario_df = pd.DataFrame(_scenario_rows)
        _lines = (
            alt.Chart(_scenario_df)
            .mark_line(point=True)
            .encode(
                x=alt.X("year:O", title="Year"),
                y=alt.Y("z:Q", title="Estimated change (dwellings)"),
                color=alt.Color("scenario:N", title="Scenario (posterior weight)"),
            )
        )
        _year_chart = mo.ui.altair_chart(
            (_band + _lines).properties(
                width=650, height=280,
                title=f"{{_area}} -- estimated change per year, by scenario "
                      f"(grey band: overall 90% CI)",
            )
        )
    else:
        _line = (
            alt.Chart(_year_rows)
            .mark_line(point=True)
            .encode(
                x=alt.X("year:O", title="Year"),
                y=alt.Y("z_mean:Q", title="Estimated change (dwellings)"),
            )
        )
        _year_chart = mo.ui.altair_chart(
            (_band + _line).properties(
                width=650, height=280,
                title=f"{{_area}} -- estimated change per year (90% CI band)",
            )
        )

    if _tier_row["tier"] == "tier1":
        _panel = mo.vstack(
            [
                mo.md(
                    f"**{{_area}}** ({{_tier_row['borough_name']}}) -- Tier 1, confident. "
                    f"Decade total: {{_tier_row['D']:.0f}} dwellings."
                ),
                _year_chart,
            ]
        )
    elif _tier_row["tier"] == "tier2" and _tier_row["tier_subtype"] == "resolved":
        _scenarios = area_scenarios[area_scenarios["area"] == _area]
        _lines = [
            f"- **{{r.scenario_label}}** ({{r.weight:.0%}} of the posterior): concentrated in "
            f"**{{int(r.peak_year)}}** (~{{r.peak_year_z:.0f}} dwellings that year)"
            for r in _scenarios.itertuples()
        ]
        _panel = mo.vstack(
            [
                mo.callout(
                    mo.md(
                        f"**{{_area}}** ({{_tier_row['borough_name']}}) -- Tier 2, ambiguous but "
                        f"characterizable. Decade total: {{_tier_row['D']:.0f}} dwellings. "
                        f"The model can't pin down a single year-by-year path, but the "
                        f"ambiguity resolves into distinct, labelled scenarios:\\n\\n"
                        + "\\n".join(_lines)
                    ),
                    kind="warn",
                ),
                _year_chart,
            ]
        )
    else:
        _reason = (
            "no active recorded data this decade"
            if _tier_row["tier"] == "tier3"
            else "ambiguous, but no small set of clean scenarios describes it"
        )
        _panel = mo.vstack(
            [
                mo.callout(
                    mo.md(
                        f"**{{_area}}** ({{_tier_row['borough_name']}}) -- decade total "
                        f"(Census-recorded, treated as exact this round) is "
                        f"**{{_tier_row['D']:.0f}} dwellings**, but the year-by-year breakdown is "
                        f"genuinely diffuse ({{_reason}}). Reporting the total only is the honest "
                        f"answer here, not a single-year guess."
                    ),
                    kind="neutral",
                ),
                _year_chart,
            ]
        )

    _panel
    return


if __name__ == "__main__":
    app.run()
'''

if __name__ == '__main__':
    main()
