"""
Builds notebooks/8.0-cd-az3_estimates_dashboard.py -- a marimo notebook with
Phase A's CSVs + the borough boundary GeoJSON embedded directly as
gzip+base64 string literals in its own source, so it has ZERO runtime file
or private-package dependency (no housing_projections/gla_data/geopandas
import, no filesystem read). That's required for
`marimo export html-wasm` to produce a single, truly self-contained static
HTML file that non-technical stakeholders can open with no server and no
access to this repo's private dataset -- see
docs/estimates-dashboard-report-plan.md Phase B.

Re-run this whenever results/artifacts/az3_year_estimates/*.csv or
borough_boundaries.geojson change; it always overwrites the notebook file
from scratch (the notebook itself is generated output, not hand-edited).

Usage
-----
    pixi run python scripts/build_dashboard.py
"""
import base64
import gzip
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = _REPO_ROOT / 'results' / 'artifacts' / 'az3_year_estimates'
OUTPUT_PATH = _REPO_ROOT / 'notebooks' / '8.0-cd-az3_estimates_dashboard.py'

# Regenerate lsoa_boundaries.geojson via scripts/export_lsoa_boundaries.py
# whenever the underlying LSOA geometry/outlier-exclusion changes.


def _encode(path):
    raw = path.read_bytes()
    return base64.b64encode(gzip.compress(raw, compresslevel=9)).decode('ascii')


def main():
    blobs = {
        'AREA_YEAR_ESTIMATES_GZB64': _encode(DATA_DIR / 'area_year_estimates.csv'),
        'AREA_SCENARIOS_GZB64': _encode(DATA_DIR / 'area_scenarios.csv'),
        'AREA_TIER_SUMMARY_GZB64': _encode(DATA_DIR / 'area_tier_summary.csv'),
        'BOROUGH_LONDON_TOTALS_GZB64': _encode(DATA_DIR / 'borough_london_totals.csv'),
        'BOROUGH_BOUNDARIES_GZB64': _encode(DATA_DIR / 'borough_boundaries.geojson'),
        'LSOA_BOUNDARIES_GZB64': _encode(DATA_DIR / 'lsoa_boundaries.geojson'),
    }
    for name, blob in blobs.items():
        print(f'{name}: {len(blob) / 1e3:.0f} KB (base64)')

    notebook_source = NOTEBOOK_TEMPLATE.format(**blobs)
    OUTPUT_PATH.write_text(notebook_source)
    print(f'\nWrote {OUTPUT_PATH} ({OUTPUT_PATH.stat().st_size / 1e6:.1f} MB)')


NOTEBOOK_TEMPLATE = '''import marimo

__generated_with = "0.23.4"
app = marimo.App(width="medium", app_title="AZ3 dwelling-change estimates")


@app.cell(hide_code=True)
def _():
    import marimo as mo
    return (mo,)


@app.cell(hide_code=True)
def _():
    # Generated by scripts/build_dashboard.py -- do not hand-edit the blobs
    # below. Re-run that script after Phase A's CSVs change.
    import base64
    import gzip
    import io
    import json

    import altair as alt
    import pandas as pd

    def _load_csv(b64_gz):
        raw = gzip.decompress(base64.b64decode(b64_gz))
        return pd.read_csv(io.StringIO(raw.decode("utf-8")))

    def _load_geojson(b64_gz):
        raw = gzip.decompress(base64.b64decode(b64_gz))
        return json.loads(raw.decode("utf-8"))

    _AREA_YEAR_ESTIMATES_GZB64 = "{AREA_YEAR_ESTIMATES_GZB64}"
    _AREA_SCENARIOS_GZB64 = "{AREA_SCENARIOS_GZB64}"
    _AREA_TIER_SUMMARY_GZB64 = "{AREA_TIER_SUMMARY_GZB64}"
    _BOROUGH_LONDON_TOTALS_GZB64 = "{BOROUGH_LONDON_TOTALS_GZB64}"
    _BOROUGH_BOUNDARIES_GZB64 = "{BOROUGH_BOUNDARIES_GZB64}"
    _LSOA_BOUNDARIES_GZB64 = "{LSOA_BOUNDARIES_GZB64}"

    area_year_estimates = _load_csv(_AREA_YEAR_ESTIMATES_GZB64)
    area_scenarios = _load_csv(_AREA_SCENARIOS_GZB64)
    area_tier_summary = _load_csv(_AREA_TIER_SUMMARY_GZB64)
    borough_london_totals = _load_csv(_BOROUGH_LONDON_TOTALS_GZB64)
    borough_boundaries = _load_geojson(_BOROUGH_BOUNDARIES_GZB64)
    lsoa_boundaries = _load_geojson(_LSOA_BOUNDARIES_GZB64)
    return (
        alt,
        area_scenarios,
        area_tier_summary,
        area_year_estimates,
        borough_boundaries,
        borough_london_totals,
        json,
        lsoa_boundaries,
        pd,
    )


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
        # London dwelling-stock change, 2012-2021 -- AZ3 model estimates

        Every figure here comes from a statistical model's estimate of annual dwelling-stock
        change (`z`) per London LSOA, reconciled against multiple administrative records.
        For this round of modelling, the 2011/2021 Census totals are treated as exactly
        correct -- a deliberate simplifying assumption, not a claim that the Census itself has
        zero error; that assumption could be relaxed in future work. Given that assumption, the
        **total** change over the decade adds no further modelling uncertainty for any area;
        the **year-by-year breakdown** within that decade is not equally certain everywhere, so
        every area below is labelled with one of three confidence tiers:

        - **Tier 1 -- Confident**: a single trustworthy year-by-year path.
        - **Tier 2 -- Ambiguous, resolved**: 2-3 distinct, labelled possible stories (e.g.
          "60% chance the change concentrated in 2019, 40% chance 2021"), each with its
          relative likelihood.
        - **Tier 2 -- Ambiguous, unresolved / Tier 3 -- Diffuse**: the total change carries no
          further modelling uncertainty (under the assumption above) but no small set of
          clean stories describes the year-by-year pattern -- reported as the total only, not
          a misleading single-year guess.
        """
    )
    return


@app.cell(hide_code=True)
def _(area_tier_summary, borough_london_totals, mo):
    _london_total = borough_london_totals[
        (borough_london_totals["geography"] == "London")
        & (borough_london_totals["year"] == "total")
    ].iloc[0]

    _n = len(area_tier_summary)
    _tier_counts = area_tier_summary["tier"].value_counts()
    _pct_tier1 = 100 * _tier_counts.get("tier1", 0) / _n
    _pct_tier2 = 100 * _tier_counts.get("tier2", 0) / _n
    _pct_tier3 = 100 * _tier_counts.get("tier3", 0) / _n

    mo.hstack(
        [
            mo.stat(
                value=f"{{_london_total['z_total_mean']:,.0f}}",
                label="London total dwelling change 2012-2021",
                caption=(
                    f"90% CI: {{_london_total['z_total_lo90']:,.0f}} to "
                    f"{{_london_total['z_total_hi90']:,.0f}}"
                ),
            ),
            mo.stat(value=f"{{_pct_tier1:.0f}}%", label="Areas confident (Tier 1)"),
            mo.stat(value=f"{{_pct_tier2:.0f}}%", label="Areas with labelled scenarios (Tier 2)"),
            mo.stat(value=f"{{_pct_tier3:.0f}}%", label="Areas diffuse / total-only (Tier 3)"),
        ],
        justify="space-around",
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        """
        ## Which kinds of areas tend to be less certain?

        Confidence in the year-by-year picture is not random -- it depends strongly on how
        much change an area had to account for, and only weakly on which borough it's in.
        """
    )
    return


@app.cell(hide_code=True)
def _(area_tier_summary, pd):
    _bins = [0, 10, 25, 50, 100, 250, 1e9]
    _labels = ["0-10", "10-25", "25-50", "50-100", "100-250", "250+"]
    _tmp = area_tier_summary.copy()
    _tmp["abs_D"] = _tmp["D"].abs()
    _tmp["D_band"] = pd.cut(_tmp["abs_D"], bins=_bins, labels=_labels, include_lowest=True)
    d_band_stats = (
        _tmp.groupby("D_band")["tier"]
        .value_counts(normalize=True)
        .unstack(fill_value=0)
        .reset_index()
        .melt(id_vars="D_band", var_name="tier", value_name="fraction")
    )
    d_band_stats["fraction"] = d_band_stats["fraction"] * 100
    return (d_band_stats,)


@app.cell(hide_code=True)
def _(alt, d_band_stats, mo):
    _band_order = ["0-10", "10-25", "25-50", "50-100", "100-250", "250+"]
    _tier_labels = {{
        "tier1": "Confident", "tier2": "Labelled scenarios", "tier3": "Diffuse / total-only"
    }}
    _named = d_band_stats.copy()
    _named["tier_label"] = _named["tier"].map(_tier_labels)

    _chart = (
        alt.Chart(_named)
        .mark_bar()
        .encode(
            x=alt.X("D_band:N", title="Size of decade change (dwellings, absolute)",
                    sort=_band_order),
            y=alt.Y("fraction:Q", title="% of areas"),
            color=alt.Color(
                "tier_label:N", title="Confidence group",
                scale=alt.Scale(
                    domain=["Confident", "Labelled scenarios", "Diffuse / total-only"],
                    range=["#4c78a8", "#f2a900", "#b3b3b3"],
                ),
            ),
            tooltip=["D_band", "tier_label", alt.Tooltip("fraction:Q", format=".0f")],
        )
        .properties(width=600, height=280, title="Confidence group by size of change")
    )
    mo.vstack(
        [
            _chart,
            mo.md(
                "*Smaller changes are either very confidently tracked or, if there was next to "
                "no recorded activity behind them, diffuse; the largest changes are almost "
                "always ambiguous between a few labelled scenarios rather than confidently "
                "pinned to one year.*"
            ),
        ]
    )
    return


@app.cell(hide_code=True)
def _(alt, borough_stats, mo):
    _chart = (
        alt.Chart(borough_stats)
        .mark_bar()
        .encode(
            x=alt.X("pct_tier1:Q", title="% of areas confident (Tier 1)"),
            y=alt.Y("borough_name:N", title=None, sort="-x"),
            color=alt.Color("D_total:Q", title="Total change", scale=alt.Scale(scheme="blues")),
            tooltip=[
                "borough_name",
                alt.Tooltip("pct_tier1:Q", format=".0f"),
                alt.Tooltip("D_total:Q", title="Total change", format=",.0f"),
            ],
        )
        .properties(width=600, height=520, title="Confidence by borough")
    )
    mo.vstack(
        [
            _chart,
            mo.md(
                "*Boroughs with more total change to account for (darker bars) tend to have "
                "fewer confidently-tracked areas -- the same size-of-change pattern as above, "
                "not a borough-specific effect.*"
            ),
        ]
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md("""## Explore by borough""")
    return


@app.cell(hide_code=True)
def _(area_tier_summary):
    _borough_tier_counts = (
        area_tier_summary.groupby("borough_name")["tier"]
        .value_counts(normalize=True)
        .unstack(fill_value=0)
        * 100
    )
    borough_stats = (
        area_tier_summary.groupby("borough_name")
        .agg(n_areas=("area", "size"), D_total=("D", "sum"))
        .join(_borough_tier_counts)
        .reset_index()
        .rename(columns={{"tier1": "pct_tier1", "tier2": "pct_tier2", "tier3": "pct_tier3"}})
    )
    for _col in ["pct_tier1", "pct_tier2", "pct_tier3"]:
        if _col not in borough_stats.columns:
            borough_stats[_col] = 0.0
    return (borough_stats,)


@app.cell(hide_code=True)
def _(mo):
    map_metric = mo.ui.dropdown(
        options={{
            "% of areas confident (Tier 1)": "pct_tier1",
            "% of areas diffuse / total-only (Tier 3)": "pct_tier3",
            "Total dwelling change (decade)": "D_total",
        }},
        value="% of areas confident (Tier 1)",
        label="Colour boroughs by",
    )
    map_metric
    return (map_metric,)


@app.cell(hide_code=True)
def _(alt, borough_boundaries, borough_stats, map_metric):
    _chart = (
        alt.Chart(alt.Data(values=borough_boundaries["features"]))
        .mark_geoshape(stroke="white", strokeWidth=0.5)
        .transform_lookup(
            lookup="properties.borough_name",
            from_=alt.LookupData(
                borough_stats, "borough_name", ["pct_tier1", "pct_tier2", "pct_tier3", "D_total"]
            ),
        )
        .encode(
            color=alt.Color(f"{{map_metric.value}}:Q", title=map_metric.selected_key),
            tooltip=[
                alt.Tooltip("properties.borough_name:N", title="Borough"),
                alt.Tooltip("pct_tier1:Q", title="% Tier 1", format=".0f"),
                alt.Tooltip("pct_tier2:Q", title="% Tier 2", format=".0f"),
                alt.Tooltip("pct_tier3:Q", title="% Tier 3", format=".0f"),
                alt.Tooltip("D_total:Q", title="Total change", format=",.0f"),
            ],
        )
        .properties(width=520, height=420, title="London boroughs")
    )
    _chart
    return


@app.cell(hide_code=True)
def _(borough_london_totals, mo):
    borough_choice = mo.ui.dropdown(
        options=sorted(borough_london_totals["geography"].unique()),
        value="London",
        label="Drill down to a borough (drives the map, trend chart and LSOA table below)",
    )
    borough_choice
    return (borough_choice,)


@app.cell(hide_code=True)
def _(alt, area_tier_summary, borough_boundaries, borough_choice, lsoa_boundaries, mo, pd):
    if borough_choice.value == "London":
        _content = mo.md(
            "*Pick a borough above to see its LSOA-level detail map (all of London at "
            "once is too much detail to render usefully here -- use the borough map "
            "above for the London-wide view).*"
        )
    else:
        # Small locator map -- plain grey London boroughs with the selected one
        # highlighted, so it's clear where in London this LSOA detail sits without
        # having to cross-reference the borough choropleth further up.
        _locator_df = pd.DataFrame(
            {{"borough_name": [f["properties"]["borough_name"] for f in borough_boundaries["features"]]}}
        )
        _locator_df["selected"] = _locator_df["borough_name"] == borough_choice.value

        _locator = (
            alt.Chart(alt.Data(values=borough_boundaries["features"]))
            .mark_geoshape(stroke="white", strokeWidth=0.4)
            .transform_lookup(
                lookup="properties.borough_name",
                from_=alt.LookupData(_locator_df, "borough_name", ["selected"]),
            )
            .encode(
                color=alt.Color(
                    "selected:N", legend=None,
                    scale=alt.Scale(domain=[True, False], range=["#e41a1c", "#d9d9d9"]),
                ),
            )
            .properties(width=150, height=130)
        )

        _tier_labels = {{
            "tier1": "Confident", "tier2": "Labelled scenarios", "tier3": "Diffuse / total-only"
        }}
        _lsoa_colour = area_tier_summary[["area", "tier"]].copy()
        _lsoa_colour["tier_label"] = _lsoa_colour["tier"].map(_tier_labels)

        _features = [
            f for f in lsoa_boundaries["features"]
            if f["properties"]["borough_name"] == borough_choice.value
        ]

        _chart = (
            alt.Chart(alt.Data(values=_features))
            .mark_geoshape(stroke="white", strokeWidth=0.3)
            .transform_lookup(
                lookup="properties.LSOA21CD",
                from_=alt.LookupData(_lsoa_colour, "area", ["tier_label"]),
            )
            .encode(
                color=alt.Color(
                    "tier_label:N", title="Confidence group",
                    scale=alt.Scale(
                        domain=["Confident", "Labelled scenarios", "Diffuse / total-only"],
                        range=["#4c78a8", "#f2a900", "#b3b3b3"],
                    ),
                ),
                tooltip=[
                    alt.Tooltip("properties.LSOA21CD:N", title="LSOA"),
                    alt.Tooltip("tier_label:N", title="Confidence group"),
                ],
            )
            .properties(width=520, height=420, title=f"LSOA-level detail -- {{borough_choice.value}}")
        )
        _content = mo.vstack(
            [
                mo.hstack([_chart, _locator], justify="start", gap=2, align="start"),
                mo.md(
                    "*This map isn't clickable -- use the LSOA search/table further down "
                    "to look up a specific area's detail.*"
                ),
            ]
        )
    _content
    return


@app.cell(hide_code=True)
def _(alt, borough_choice, borough_london_totals, mo):
    _trend = borough_london_totals[
        (borough_london_totals["geography"] == borough_choice.value)
        & (borough_london_totals["year"] != "total")
    ].copy()
    _trend["year"] = _trend["year"].astype(int)

    _band = (
        alt.Chart(_trend)
        .mark_area(opacity=0.25)
        .encode(x=alt.X("year:O", title="Year"), y="z_total_lo90:Q", y2="z_total_hi90:Q")
    )
    _line = (
        alt.Chart(_trend)
        .mark_line(point=True)
        .encode(x=alt.X("year:O", title="Year"), y=alt.Y("z_total_mean:Q", title="Dwelling change"))
    )
    mo.ui.altair_chart(
        (_band + _line).properties(
            width=650, height=280, title=f"{{borough_choice.value}} -- annual dwelling change (90% CI)"
        )
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md("""## Look up a specific LSOA""")
    return


@app.cell(hide_code=True)
def _(mo):
    lsoa_search = mo.ui.text(placeholder="e.g. E01002702", label="LSOA code")
    mo.hstack(
        [
            lsoa_search,
            mo.md("*Borough filter uses the selector above, next to the map.*"),
        ],
        justify="start", gap=2,
    )
    return (lsoa_search,)


@app.cell(hide_code=True)
def _(area_tier_summary, borough_choice, lsoa_search, mo):
    _filtered = area_tier_summary
    if borough_choice.value != "London":
        _filtered = _filtered[_filtered["borough_name"] == borough_choice.value]
    if lsoa_search.value.strip():
        _filtered = _filtered[
            _filtered["area"].str.contains(lsoa_search.value.strip(), case=False, na=False)
        ]
    _cols = ["area", "borough_name", "D", "tier", "tier_subtype"]
    lsoa_table = mo.ui.table(_filtered[_cols].reset_index(drop=True), selection="multi", page_size=8)
    lsoa_table
    return (lsoa_table,)


@app.cell(hide_code=True)
def _(alt, area_scenarios, area_tier_summary, area_year_estimates, json, lsoa_table, mo, pd):
    mo.stop(
        len(lsoa_table.value) == 0,
        mo.md("*Select up to 5 rows above to see each one's year-by-year breakdown, "
              "stacked below.*"),
    )

    _MAX_SELECTED = 5

    def _build_area_panel(_area):
        _tier_row = area_tier_summary[area_tier_summary["area"] == _area].iloc[0]
        _year_rows = area_year_estimates[area_year_estimates["area"] == _area].sort_values("year")
        _years = _year_rows["year"].tolist()

        _is_resolved_tier2 = _tier_row["tier"] == "tier2" and _tier_row["tier_subtype"] == "resolved"
        _d_val = _tier_row["D"]

        # P_obs/E_obs bars, faded continuously by the model's noise-mixture posterior
        # probability that each observation is a data anomaly rather than a real change
        # (opaque = trusted, faded = likely anomaly) -- same convention as
        # scripts/stakeholder_example_plots.py's static charts. Altair's own continuous
        # opacity legend renders as a labelled gradient, so the probability is
        # interpretable numerically, not just qualitatively.
        _pe_rows = []
        for _row in _year_rows.itertuples():
            _pe_rows.append({{"year": _row.year, "source": "Planning",
                              "obs": _row.P_obs, "resp_noise": _row.resp_noise_P}})
            _pe_rows.append({{"year": _row.year, "source": "UPRN",
                              "obs": _row.E_obs, "resp_noise": _row.resp_noise_E}})
        _pe_df = pd.DataFrame(_pe_rows)
        # Altair embeds every column of a chart's source dataframe into the spec,
        # not just the ones actually encoded -- so passing the full _year_rows
        # (which also carries tier/tier_subtype/borough_name etc.) leaks
        # tier_subtype's NaN (blank for every tier1/tier3 area) into the chart's
        # data, even though nothing here encodes that column. Altair 6.x happens
        # to sanitize NaN across a whole dataframe before JSON-encoding it, so
        # this is invisible locally, but the older Altair (5.x) that marimo's
        # WASM export currently resolves in Pyodide does not, and Altair's
        # strict chart_to_json (allow_nan=False) then throws -- surfacing in the
        # browser as an untraceable "internal error" on every tier1/tier3 area.
        # Restricting to just the encoded columns sidesteps the version gap
        # entirely rather than depending on either version's NaN handling.
        _year_rows_chart = _year_rows[["year", "z_mean", "z_lo90", "z_hi90"]]

        _bars = (
            alt.Chart(_pe_df)
            .mark_bar()
            .encode(
                x=alt.X("year:O", title="Year"),
                xOffset="source:N",
                y=alt.Y("obs:Q", title="Observed value"),
                color=alt.Color("source:N", title="Data source",
                                scale=alt.Scale(domain=["Planning", "UPRN"],
                                                range=["steelblue", "coral"])),
                opacity=alt.Opacity("resp_noise:Q", title="P(data anomaly)",
                                    scale=alt.Scale(domain=[0, 1], range=[0.9, 0.15])),
                tooltip=[
                    "year", "source",
                    alt.Tooltip("obs:Q", title="Observed value"),
                    alt.Tooltip("resp_noise:Q", title="P(data anomaly)", format=".0%"),
                ],
            )
        )

        _band = (
            alt.Chart(_year_rows_chart)
            .mark_area(opacity=0.12 if _is_resolved_tier2 else 0.25, color="gray")
            .encode(x=alt.X("year:O", title="Year"), y="z_lo90:Q", y2="z_hi90:Q")
        )

        if _is_resolved_tier2:
            _scenarios = area_scenarios[area_scenarios["area"] == _area]
            _scenario_rows = []
            for r in _scenarios.itertuples():
                _profile = json.loads(r.year_profile)
                for _yr, _z in zip(_years, _profile):
                    _scenario_rows.append(
                        {{"year": _yr, "z": _z, "scenario": f"{{r.scenario_label}} ({{r.weight:.0%}})"}}
                    )
            _scenario_df = pd.DataFrame(_scenario_rows)
            _lines = (
                alt.Chart(_scenario_df)
                .mark_line(point=True)
                .encode(
                    x=alt.X("year:O", title="Year"),
                    y=alt.Y("z:Q", title="Estimated change (dwellings)"),
                    # Distinct from the Planning/UPRN bar colours (steelblue/coral) above --
                    # same green/purple pair already validated for scenarios in
                    # plots/core.py's _SCENARIO_COLOURS and scripts/stakeholder_example_plots.py.
                    color=alt.Color("scenario:N", title="Scenario (posterior weight)",
                                    scale=alt.Scale(range=["#4daf4a", "#984ea3"])),
                )
            )
            # Plain chart object, not mo.ui.altair_chart -- same accommodation the
            # borough choropleth above already needed: marimo's altair_chart wrapper
            # drops the continuous opacity (P(anomaly)) legend entirely (confirmed by
            # comparing against the identical spec rendered outside marimo, where it
            # shows correctly). Nothing reads a selection from this chart, so the
            # wrapper's interactivity isn't needed anyway.
            _year_chart = (_bars + _band + _lines).resolve_scale(color="independent").properties(
                width=650, height=320,
                title=f"{{_area}}  (D={{_d_val:.0f}}) -- estimated change per year, by "
                      f"scenario (grey band: overall 90% CI)",
            )
        else:
            _line = (
                alt.Chart(_year_rows_chart)
                .mark_line(point=True, color="black")
                .encode(
                    x=alt.X("year:O", title="Year"),
                    y=alt.Y("z_mean:Q", title="Estimated change (dwellings)"),
                )
            )
            _year_chart = (_bars + _band + _line).resolve_scale(color="independent").properties(
                width=650, height=320,
                title=f"{{_area}}  (D={{_d_val:.0f}}) -- estimated change per year "
                      f"(90% CI band)",
            )

        if _tier_row["tier"] == "tier1":
            _panel = mo.vstack(
                [
                    mo.md(
                        f"**{{_area}}** ({{_tier_row['borough_name']}}) -- Tier 1, confident. "
                        f"Decade total: {{_tier_row['D']:.0f}} dwellings."
                    ),
                    _year_chart,
                ]
            )
        elif _tier_row["tier"] == "tier2" and _tier_row["tier_subtype"] == "resolved":
            _scenarios = area_scenarios[area_scenarios["area"] == _area]
            _lines = [
                f"- **{{r.scenario_label}}** ({{r.weight:.0%}} of the posterior): concentrated in "
                f"**{{int(r.peak_year)}}** (~{{r.peak_year_z:.0f}} dwellings that year)"
                for r in _scenarios.itertuples()
            ]
            _panel = mo.vstack(
                [
                    mo.callout(
                        mo.md(
                            f"**{{_area}}** ({{_tier_row['borough_name']}}) -- Tier 2, ambiguous but "
                            f"characterizable. Decade total: {{_tier_row['D']:.0f}} dwellings. "
                            f"The model can't pin down a single year-by-year path, but the "
                            f"ambiguity resolves into distinct, labelled scenarios:\\n\\n"
                            + "\\n".join(_lines)
                        ),
                        kind="warn",
                    ),
                    _year_chart,
                ]
            )
        elif (
            _tier_row["tier"] == "tier2"
            and _tier_row["tier_subtype"] == "unresolved"
            and pd.notna(_tier_row["frac_flagged_magnitude"])
            and _tier_row["frac_flagged_magnitude"] < 0.25
        ):
            _flagged_set = set(_tier_row["flagged_years"].split(","))
            _dominant = (
                _year_rows[~_year_rows["year"].astype(str).isin(_flagged_set)]
                .assign(abs_z=lambda d: d["z_mean"].abs())
                .sort_values("abs_z", ascending=False)
                .head(2)
            )
            _dominant_desc = ", ".join(
                f"{{int(row.year)}} (~{{row.z_mean:.0f}})" for row in _dominant.itertuples()
            )
            _panel = mo.vstack(
                [
                    mo.callout(
                        mo.md(
                            f"**{{_area}}** ({{_tier_row['borough_name']}}) -- Tier 2, mostly "
                            f"confident. Decade total: {{_tier_row['D']:.0f}} dwellings. Most of "
                            f"this area's year-by-year pattern is well pinned down -- the "
                            f"dominant year(s) are **{{_dominant_desc}}**. The only unresolved "
                            f"ambiguity is in **{{_tier_row['flagged_years']}}**, which together "
                            f"account for only ~{{_tier_row['frac_flagged_magnitude']:.0%}} of the "
                            f"decade's total change -- so treat those specific year(s) as "
                            f"indicative only, not the rest of the chart."
                        ),
                        kind="info",
                    ),
                    _year_chart,
                ]
            )
        else:
            _reason = (
                "no active recorded data this decade"
                if _tier_row["tier"] == "tier3"
                else "ambiguous, but no small set of clean scenarios describes it"
            )
            _panel = mo.vstack(
                [
                    mo.callout(
                        mo.md(
                            f"**{{_area}}** ({{_tier_row['borough_name']}}) -- decade total "
                            f"(Census-recorded, treated as exact this round) is "
                            f"**{{_tier_row['D']:.0f}} dwellings**, but the year-by-year breakdown is "
                            f"genuinely diffuse ({{_reason}})."
                        ),
                        kind="neutral",
                    ),
                    _year_chart,
                ]
            )
        return _panel

    _selected = lsoa_table.value
    _blocks = []
    if len(_selected) > _MAX_SELECTED:
        _blocks.append(
            mo.callout(
                mo.md(
                    f"You selected {{len(_selected)}} LSOAs -- showing the first "
                    f"{{_MAX_SELECTED}}. Deselect some rows above to see different ones."
                ),
                kind="warn",
            )
        )
        _selected = _selected.iloc[:_MAX_SELECTED]

    _blocks.extend(_build_area_panel(_a) for _a in _selected["area"])
    mo.vstack(_blocks, gap=3)
    return


if __name__ == "__main__":
    app.run()
'''

if __name__ == '__main__':
    main()
